# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/odyssey',
                'doc_host': 'https://matt-humphrey.github.io',
                'git_url': 'https://github.com/matt-humphrey/odyssey',
                'lib_path': 'odyssey'},
  'syms': {'odyssey.core': {'odyssey.core.foo': ('core.html#foo', 'odyssey/core.py')}}}
